{"master": [{"commit_oid": "1dd40f17f3b0d37e3779b6ad5041bab335142337", "commit_date": "2023-08-11T17:25:03Z", "commit_message": "CI: python 3.11 stable (#553)\n\n* CI: Python 3.11 stable\r\n* test with latest aiohttp with Python 3.11 support", "commit_author": "", "message_analysis": {"glm6b_2": [], "manual": [], "noob_engine": []}}, {"commit_oid": "7783f1c5d9d6e821f4f05dffccee504875c179d2", "commit_date": "2023-01-15T16:27:26Z", "commit_message": "Fixup CI (#520)\n\n* Report exception on flake8 and mypy failures\r\n* skip test_remote_shutdown_receives_trailing_data() on linux <3.11\r\n* pyOpenSSL~=23.0.0", "commit_author": "", "message_analysis": {"glm6b_2": [], "manual": [], "noob_engine": []}}]}